# Mapping language names to their respective language codes
languages = {
    "Dutch (Belgium)": "nl-BE",
    "Dutch (Belgium) Short": "nl-BE_short",
    "Dutch (Netherlands)": "nl-NL",
    "Dutch (Netherlands) Short": "nl-NL_short",
    "English (Australia)": "en-AU",
    "English (Australia) Short": "en-AU_short",
    "English (Canada)": "en-CA",
    "English (Canada) Short": "en-CA_short",
    "English (Hong Kong)": "en-HK",
    "English (Hong Kong) Short": "en-HK_short",
    "English (India)": "en-IN",
    "English (India) Short": "en-IN_short",
    "English (Ireland)": "en-IE",
    "English (Ireland) Short": "en-IE_short",
    "English (New Zealand)": "en-NZ",
    "English (New Zealand) Short": "en-NZ_short",
    "English (Pakistan)": "en-PK",
    "English (Pakistan) Short": "en-PK_short",
    "English (Singapore)": "en-SG",
    "English (Singapore) Short": "en-SG_short",
    "English (United Kingdom)": "en-GB",
    "English (United Kingdom) Short": "en-GB_short",
    "English (United States)": "en-US",
    "English (United States) Short": "en-US_short",
    "French (Belgium)": "fr-BE",
    "French (Belgium) Short": "fr-BE_short",
    "French (Canada)": "fr-CA",
    "French (Canada) Short": "fr-CA_short",
    "French (France)": "fr-FR",
    "French (France) Short": "fr-FR_short",
    "French (Switzerland)": "fr-CH",
    "French (Switzerland) Short": "fr-CH_short",
    "German (Austria)": "de-AT",
    "German (Austria) Short": "de-AT_short",
    "German (Germany)": "de-DE",
    "German (Germany) Short": "de-DE_short",
    "German (Switzerland)": "de-CH",
    "German (Switzerland) Short": "de-CH_short",
    "Hindi (India)": "hi-IN",
    "Hindi (India) Short": "hi-IN_short",
    "Italian (Italy)": "it-IT",
    "Italian (Italy) Short": "it-IT_short",
    "Italian (Switzerland)": "it-CH",
    "Italian (Switzerland) Short": "it-CH_short",
    "Japanese (Japan)": "ja-JP",
    "Japanese (Japan) Short": "ja-JP_short",
    "Korean (South Korea)": "ko-KR",
    "Korean (South Korea) Short": "ko-KR_short",
    "Portuguese (Brazil)": "pt-BR",
    "Portuguese (Brazil) Short": "pt-BR_short",
    "Portuguese (Portugal)": "pt-PT",
    "Portuguese (Portugal) Short": "pt-PT_short",
    "Spanish (Argentina)": "es-AR",
    "Spanish (Argentina) Short": "es-AR_short",
    "Spanish (Bolivia)": "es-BO",
    "Spanish (Bolivia) Short": "es-BO_short",
    "Spanish (Chile)": "es-CL",
    "Spanish (Chile) Short": "es-CL_short",
    "Spanish (Colombia)": "es-CO",
    "Spanish (Colombia) Short": "es-CO_short",
    "Spanish (Costa Rica)": "es-CR",
    "Spanish (Costa Rica) Short": "es-CR_short",
    "Spanish (Dominican Republic)": "es-DO",
    "Spanish (Dominican Republic) Short": "es-DO_short",
    "Spanish (Ecuador)": "es-EC",
    "Spanish (Ecuador) Short": "es-EC_short",
    "Spanish (El Salvador)": "es-SV",
    "Spanish (El Salvador) Short": "es-SV_short",
    "Spanish (Guatemala)": "es-GT",
    "Spanish (Guatemala) Short": "es-GT_short",
    "Spanish (Honduras)": "es-HN",
    "Spanish (Honduras) Short": "es-HN_short",
    "Spanish (Mexico)": "es-MX",
    "Spanish (Mexico) Short": "es-MX_short",
    "Spanish (Nicaragua)": "es-NI",
    "Spanish (Nicaragua) Short": "es-NI_short",
    "Spanish (Panama)": "es-PA",
    "Spanish (Panama) Short": "es-PA_short",
    "Spanish (Peru)": "es-PE",
    "Spanish (Peru) Short": "es-PE_short",
    "Spanish (Puerto Rico)": "es-PR",
    "Spanish (Puerto Rico) Short": "es-PR_short",
    "Spanish (Spain)": "es-ES",
    "Spanish (Spain) Short": "es-ES_short",
    "Spanish (United States)": "es-US",
    "Spanish (United States) Short": "es-US_short",
    "Spanish (Uruguay)": "es-UY",
    "Spanish (Uruguay) Short": "es-UY_short",
    "Spanish (Venezuela)": "es-VE",
    "Spanish (Venezuela) Short": "es-VE_short"
}