# Mapping language names to their respective language codes
languages = {
    "Afrikaans": "af-ZA",
    "Arabic": "ar-XA",
    "Basque": "eu-ES",
    "Bengali": "bn-IN",
    "Bulgarian": "bg-BG",
    "Catalan": "ca-ES",
    "Chinese":"yue-HK",
    "Czech": "cs-CZ",
    "Danish": "da-DK",
    "Danish": "da-DK",
    "Dutch": "nl-BE",
    "English (Australia)": "en-AU",
    "English (UK)":	"en-GB",
    "English (US)":	"en-US",
    "Filipino":	"fil-PH",
    "Finnish": "fi-FI",
    "French": "fr-FR",
    "Galician": "gl-ES",
    "German": "de-DE",
    "Greek": "el-GR",
    "Gujarati":	"gu-IN",
    "Hebrew": "he-IL",
    "Hindi": "hi-IN",
    "Hungarian": "hu-HU",
    "Icelandic": "is-IS",
    "Indonesian": "id-ID",
    "Italian": "it-IT",
    "Japanese": "ja-JP",
    "Kannada": "kn-IN",
    "Korean": "ko-KR",
    "Latvian": "lv-LV",
    "Lithuanian": "lt-LT",
    "Malayalam": "ml-IN",
    "Mandarin":	"cmn-CN",
    "Marathi": "nb-NO",
    "Polish": "pl-PL",
    "Portuguese": "pt-BR",
    "Punjabi": "pa-IN",
    "Romanian":	"ro-RO",
    "Russian": "ru-RU",
    "Serbian": "sr-RS",
    "Slovak": "sk-SK",
    "Spanish": "es-ES",
    "Swedish": "sv-SE",
    "Tamil": "ta-IN",
    "Telugu": "te-IN",
    "Telugu": "te-IN",
    "Thai": "th-TH",
    "Turkish": "tr-TR",
    "Ukrainian": "uk-UA",
    "Vietnamese": "vi-VN",
}